export default {
	itemSpacing: ["m-2", "w-auto"].join(" "),
	itemContainer: [
		"w-full",
		"max-w-sm",
		"bg-white",
		"rounded-lg",
		"shadow-md",
		"dark:border-gray-700",
	].join(" "),
	thumbnail: ["w-full"].join(" "),
	itemDetails: ["px-5", "pb-5"].join(" "),
	buttonFlex: ["flex", "items-center", "justify-center"].join(" "),
	buttonContainer: [
		"text-gray-700",
		"border",
		"border-grey-500",
		"flex",
		"justify-between",
		"items-center",
		"px-4",
		"py-2",
		"w-full",
	].join(" "),
	quantityButton: [
		"flex",
		"text-white",
		"bg-emerald-500",
		"border-0",
		"py-2",
		"px-6",
		"focus:outline-none",
		"hover:bg-emerald-600",
		"rounded",
		"w-10",
		"justify-center",
	].join(" "),
	quantity: ["text-gray-700", "font-bold", "text-xl"].join(" "),
	itemTotal: ["ml-5"].join(" ")
};
