export default {
  paymentContainer: ["w-full", "max-w-sm"].join(" "),
  paymentColumn: ["flex", "items-center", "justify-center", "k", "mb-6"].join(
    " "
  ),
  paymentLayout: ["md:w-1/3"].join(" "),
  labelDesign: [
    "block",
    "text-gray-500",
    "font-bold",
    "md:text-right",
    "mb-1",
    "md:mb-0",
    "pr-4",
  ].join(" "),
  currencyErrorMessageColumn: ["md:w-2/3"].join(" "),
  errorMessageColor: ["text-red-500"].join(" "),
  currencyErrorMessageInput: [
    "appearance-none",
    "border-2",
    "border-gray-200",
    "rounded",
    "w-full",
    "py-2",
    "px-4",
    "text-gray-700",
    "leading-tight",
    "focus:outline-none",
    "focus:bg-white",
    "focus:border-purple-500",
  ].join(" "),
  paymentSourceColumn: ["flex", "items-center", "mb-6"].join(" "),
  paymentSourceLayout: ["md:w-1/3"].join(" "),
  paymentSourceLabel: [
    "block",
    "text-gray-500",
    "font-bold",
    "md:text-right",
    "mb-1",
    "md:mb-0",
    "pr-4",
  ].join(" "),
  sourceErrorMessageColumn: ["md:w-2/3"].join(" "),
  sourceErrorMessageInput: [
    "appearance-none",
    "border-2",
    "border-gray-200",
    "rounded",
    "w-full",
    "py-2",
    "px-4",
    "text-gray-700",
    "leading-tight",
    "focus:outline-none",
    "focus:bg-white",
    "focus:border-purple-500",
  ].join(" "),
  submitColumn: ["md:flex", "md:items-center", "justify-end"].join(" "),
  submitInput: [
    "bg-blue-500",
    "hover:bg-blue-700",
    "text-white",
    "font-bold",
    "py-2",
    "px-4",
    "rounded",
  ].join(" "),
};
